import Head from "next/head";
import { Inter } from "@next/font/google";
import { useTrick } from "@/hooks/useTrick";
import { When } from "../components/shared/When";

export default function Home() {
  const { handleClick, handleHover, noAnswerRef, youAreDumb, questionBoxRef } =
    useTrick();
  return (
    <>
      <Head>
        <title>pergunta capciosa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          "flex flex-col flex-1 w-full bg-gradient-to-tr from-cyan-500 to-blue-500  items-center"
        }
      >
        <div
          ref={questionBoxRef}
          className="flex flex-col h-fit w-fit font-sans font-bold bg-white-200 rounded-xl p-6 mt-64 gap-6 mx-6 "
        >
          <span className="text-7xl text-center w-[500px] whitespace-pre-wrap" id={"title"}>
            {!youAreDumb ? 'você é burro ?' : 'Sempre soube que você era burro \n 😂'}
          </span>
          <When value={!youAreDumb}>
            <div className="grid xl:grid-cols-2 xl:grid-rows-1 gap-6 text-white-full grid-rows-2">
              <button onClick={handleClick} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded border border-borderColor h-20 text-2xl">
                Sim
              </button>
              <button
                ref={noAnswerRef}
                onMouseOver={handleHover}
                className="relative bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded border border-borderColor h-20 text-2xl"
              >
                Não
              </button>
            </div>
          </When>
        </div>
      </main>
    </>
  );
}
